Algoritmo "Declarando Variáveis"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/5/2020
Var
// Seção de Declarações das variáveis 
   nome: caractere
   idade: inteiro
   peso: real
   estudante: logico

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nome <-"João"
   idade <- 29
   peso <- 93,5
   estudante <- verdadeiro

Fimalgoritmo